import type { Metadata } from 'next';
import { Poppins, DM_Sans, Lato } from 'next/font/google';
import './globals.css';
import Providers from './providers';
import { AuthProvider } from '@/context/AuthContext';
import { ErrorFallback } from '@/components/ErrorBoundary';
import { ErrorBoundary } from 'react-error-boundary';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
});

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-dm-sans',
});

const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
  variable: '--font-lato',
});

export const metadata: Metadata = {
  title: 'Park App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} ${poppins.variable} ${dmSans.variable} font-lato`}>
        <Providers>
          <AuthProvider>
            <ErrorBoundary FallbackComponent={ErrorFallback}>{children}</ErrorBoundary>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
